### ISSUE TITLE
Can you help me? I paid 3 days ago to add a logo but they didnt add it

### ISSUE THREAD

**Issue by ferrocker** [trustwallet/developer#136]
What can I do with this issue??? I can't see still my logo added and I already paid 3 days ago.
![Capture+_2020-06-26-07-15-49](https://user-images.githubusercontent.com/36880928/85868471-2fdd8e00-b77f-11ea-97c9-ebc1b93e4ac8.png)
![Capture+_2020-06-26-07-15-37](https://user-images.githubusercontent.com/36880928/85868478-323fe800-b77f-11ea-9508-547c86c5acaa.png)

**Comment by catenocrypt** [comment]
I can only repeat previous advice:
Please follow correct submission guidelines.
https://community.trustwallet.com/t/how-to-submit-a-new-token-asset/3863/2

Your previous pull request was unusable, due to: not created from latest, contained many other changed, logo wrong size.
Please create a new, fresh PR.  You will not need to pay again, payment to PR #2464 can be moved over.

https://github.com/trustwallet/assets/pull/2464
